export const intrests =[
    'Sports',
    'Music',
    'Movies',
    'Reading',
    'Travel',
    'Cooking',
    'Photography',
    'Art',
    'Gaming',
    'Writing',
    'Dancing',
    'Hiking',
    'Camping',
    'Fashion',
    'Technology',
    'Fitness',
    'Yoga',
    'Gardening',
    'Animals',
    'Volunteering',
    'Crafts',
    'Singing',
    'Shopping',
    'History',
    'Languages',
    'Cars',
    'Soccer',
    'Basketball',
    'Tennis',
    'Swimming',
    'Running',
    'Cycling',
    'Painting',
    'Drawing',
    'Sculpture',
    'Reading Fiction',
    'Reading Non-fiction',
    'Nature',
    'Astrology',
    'Cooking',
    'Baking',
    'Gastronomy',
    'Board Games',
    'Card Games',
    'Chess',
    'Fashion Design',
    'Interior Design',
    'DIY Projects',
    'Coding',
    'Robotics',
    'Sci-Fi',
    'Fantasy',
    'Comics',
    'Anime',
    'Cosplay',
    'Collecting',
    'Music Production',
    'Film-making',
    'Theatre',
    'Sustainable Living',
]