const QUESTIONS = [
  {
    questionText: 'Which word is a synonym for "happy"?',
    options: ['Delighted', 'Sad', 'Angry', 'Tired'],
    correctOption: 'Delighted',
    quizId: 1,
  },
  {
    questionText: 'What is the plural form of "child"?',
    options: ['Childs', 'Childrens', 'Childes', 'Children'],
    correctOption: 'Children',
    quizId: 1,
  },
  {
    questionText: 'What is the opposite of the word "hot"?',
    options: ['Cold', 'Warm', 'Cool', 'Freezing'],
    correctOption: 'Cold',
    quizId: 1,
  },
  {
    questionText: 'Which word is a verb?',
    options: ['Table', 'Happy', 'Jump', 'Book'],
    correctOption: 'Jump',
    quizId: 1,
  },
  {
    questionText: 'What is the correct spelling of the color between blue and yellow?',
    options: ['Grean', 'Green', 'Grin', 'Grien'],
    correctOption: 'Green',
    quizId: 1,
  },
  {
    questionText: 'What is the opposite of "small"?',
    options: ['Big', 'Tiny', 'Narrow', 'Short'],
    correctOption: 'Big',
    quizId: 2,
  },
  {
    questionText: 'Which word is a noun?',
    options: ['Climbing', 'Jumping', 'Swimming', 'Mountain'],
    correctOption: 'Mountain',
    quizId: 2,
  },
  {
    questionText: 'What is the comparative form of "good"?',
    options: ['Better', 'Gooder', 'Best', 'More good'],
    correctOption: 'Better',
    quizId: 2,
  },
  {
    questionText: 'What is the correct spelling of the color between yellow and blue?',
    options: ['Grean', 'Green', 'Grin', 'Grien'],
    correctOption: 'Green',
    quizId: 2,
  },
  {
    questionText: 'What is the superlative form of "funny"?',
    options: ['Funnyer', 'More funny', 'Funnier', 'Funnyest'],
    correctOption: 'Funnier',
    quizId: 2,
  },
  {
    questionText: 'What is the correct past tense of the verb "run"?',
    options: ['Runned', 'Run', 'Ran', 'Running'],
    correctOption: 'Ran',
    quizId: 3,
  },
  {
    questionText: 'What is the synonym of "happy"?',
    options: ['Delighted', 'Sad', 'Angry', 'Tired'],
    correctOption: 'Delighted',
    quizId: 3,
  },
  {
    questionText: 'Which word is an adjective?',
    options: ['Run', 'Happiness', 'Fast', 'Jump'],
    correctOption: 'Fast',
    quizId: 3,
  },
  {
    questionText: 'What is the correct order of the words in this sentence? "She the store went to yesterday."',
    options: ['She went to the store yesterday.', 'She the store went yesterday to.', 'Yesterday to the store went she.', 'Yesterday she went to the store.'],
    correctOption: 'She went to the store yesterday.',
    quizId: 3,
  },
  {
    questionText: 'What is the plural form of "mouse"?',
    options: ['Mouses', 'Mouse', 'Mice', 'Mices'],
    correctOption: 'Mice',
    quizId: 3,
  },
  {
    questionText: 'What is the present participle form of the verb "study"?',
    options: ['Study', 'Studied', 'Studying', 'Studies'],
    correctOption: 'Studying',
    quizId: 4,
  },
  {
    questionText: 'Which word is an adjective?',
    options: ['Run', 'Happiness', 'Fast', 'Jump'],
    correctOption: 'Fast',
    quizId: 4,
  },
  {
    questionText: 'What is the opposite of "light"?',
    options: ['Heavy', 'Bright', 'Dark', 'Easy'],
    correctOption: 'Heavy',
    quizId: 4,
  },
  {
    questionText: 'What is the correct order of the words in this sentence? "She to the beach went last weekend."',
    options: ['She went to the beach last weekend.', 'She to the beach went weekend last.', 'Last weekend she to the beach went.', 'Went to the beach she last weekend.'],
    correctOption: 'She went to the beach last weekend.',
    quizId: 4,
  },
  {
    questionText: 'What is the superlative form of "good"?',
    options: ['Gooder', 'Best', 'Better', 'Most good'],
    correctOption: 'Best',
    quizId: 4,
  },
  {
    questionText: 'What is the plural form of "ox"?',
    options: ['Oxen', 'Oxes', 'Oxies', 'Oxies'],
    correctOption: 'Oxen',
    quizId: 5,
  },
  {
    questionText: 'Which word is a verb?',
    options: ['Jump', 'Beautiful', 'Joyful', 'Sad'],
    correctOption: 'Jump',
    quizId: 5,
  },
  {
    questionText: 'What is the opposite of "high"?',
    options: ['Low', 'Tall', 'Short', 'Fast'],
    correctOption: 'Low',
    quizId: 5,
  },
  {
    questionText: 'What is the correct order of the words in this sentence? "Yesterday, I to the park went."',
    options: ['Yesterday I went to the park.', 'I to the park went yesterday.', 'Went to the park yesterday I.', 'The park went to I yesterday.'],
    correctOption: 'Yesterday I went to the park.',
    quizId: 5,
  },
  {
    questionText: 'Which word is an adjective?',
    options: ['Run', 'Happiness', 'Fast', 'Jump'],
    correctOption: 'Fast',
    quizId: 5,
  },
  {
    questionText: 'What is the past tense of the verb "eat"?',
    options: ['Eat', 'Ate', 'Eaten', 'Eating'],
    correctOption: 'Ate',
    quizId: 6,
  },
  {
    questionText: 'Which word is a synonym for "small"?',
    options: ['Tiny', 'Big', 'Giant', 'Huge'],
    correctOption: 'Tiny',
    quizId: 6,
  },
  {
    questionText: 'What is the opposite of "fast"?',
    options: ['Slow', 'Quick', 'Rapid', 'Swift'],
    correctOption: 'Slow',
    quizId: 6,
  },
  {
    questionText: 'What is the correct order of the words in this sentence? "I go to school every day."',
    options: ['I go to school every day.', 'Every day go I to school.', 'To school go I every day.', 'Go to school I every day.'],
    correctOption: 'I go to school every day.',
    quizId: 6,
  },
  {
    questionText: 'Which word is a noun?',
    options: ['Running', 'Happy', 'Jumping', 'Mountain'],
    correctOption: 'Mountain',
    quizId: 6,
  },
  {
    questionText: 'What is the comparative form of "good"?',
    options: ['Better', 'Gooder', 'Best', 'More good'],
    correctOption: 'Better',
    quizId: 7,
  },
  {
    questionText: 'Which word is an adjective?',
    options: ['Run', 'Happiness', 'Fast', 'Jump'],
    correctOption: 'Fast',
    quizId: 7,
  },
  {
    questionText: 'What is the opposite of "empty"?',
    options: ['Full', 'Blank', 'Void', 'Hollow'],
    correctOption: 'Full',
    quizId: 7,
  },
  {
    questionText: 'What is the correct order of the words in this sentence? "He the book reads."',
    options: ['He reads the book.', 'The book he reads.', 'Reads he the book.', 'Book the he reads.'],
    correctOption: 'He reads the book.',
    quizId: 7,
  },
  {
    questionText: 'What is the plural form of "goose"?',
    options: ['Gooses', 'Goose', 'Geese', 'Geeses'],
    correctOption: 'Geese',
    quizId: 7,
  },
  {
    questionText: 'What is the past tense of the verb "go"?',
    options: ['Go', 'Went', 'Gone', 'Going'],
    correctOption: 'Went',
    quizId: 8,
  },
  {
    questionText: 'Which word is a synonym for "happy"?',
    options: ['Joyful', 'Sad', 'Angry', 'Tired'],
    correctOption: 'Joyful',
    quizId: 8,
  },
  {
    questionText: 'What is the opposite of "hot"?',
    options: ['Cold', 'Warm', 'Cool', 'Freezing'],
    correctOption: 'Cold',
    quizId: 8,
  },
  {
    questionText: 'What is the correct order of the words in this sentence? "She to the store went yesterday."',
    options: ['She went to the store yesterday.', 'She to the store went yesterday.', 'Yesterday to the store went she.', 'Yesterday she went to the store.'],
    correctOption: 'She went to the store yesterday.',
    quizId: 8,
  },
  {
    questionText: 'What is the plural form of "mouse"?',
    options: ['Mice', 'Mouses', 'Mouse', 'Mices'],
    correctOption: 'Mice',
    quizId: 8,
  },
];

module.exports = {
  QUESTIONS,
};
