
import type { MenuProps } from 'antd';
const languages = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Dutch',
  'Russian',
  'Chinese',
  'Japanese',
  'Korean',
  'Arabic',
  'Hindi',
  'Bengali',
  'Punjabi',
  'Turkish',
  'Swedish',
  'Danish',
  'Norwegian',
  'Finnish',
  'Polish',
  'Greek',
  'Czech',
  'Hungarian',
  'Romanian',
  'Indonesian',
  'Malay',
  'Thai',
  'Vietnamese',
  'Hebrew',
  'Swahili',
  'Kiswahili',
  'Tagalog',
  'Urdu',
  'Gujarati',
  'Marathi',
  'Telugu',
  'Tamil',
  'Kannada',
  'Malayalam',
  'Odia',
  'Sinhala',
  'Burmese',
  'Khmer',
  'Lao',
  'Mongolian',
  'Nepali',
  'Sanskrit',
  'Tibetan',
  'Zulu',
];

const menuItems: MenuProps['items'] = languages.map((language, index) => ({
  label: language,
  key: `${index + 1}`,
  icon:' ll'
}));

  export default menuItems;