name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-job:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container: node:16

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: fluento
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Wait for PostgreSQL
        run: sleep 10s  # Wait for 10 seconds to ensure PostgreSQL is ready

      - name: Connect to PostgreSQL
        run: npm run test
        env:
          DB_URL: ${{ secrets.DB_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
